### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by echo66** [MTG/gaia#11]
Build failed
Traceback (most recent call last):
  File "/home/echo66/tese/features-extraction/gaia-master/.waf-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Task.py", line 123, in process
    ret=self.run()
  File "/home/echo66/tese/features-extraction/gaia-master/.waf-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Task.py", line 47, in run
    return m1(self)
  File "/home/echo66/tese/features-extraction/gaia-master/src/wscript", line 53, in write_pcfile
    open('../build/gaia2.pc', 'w').write(bld.env.pcfile)
IOError: [Errno 2] No such file or directory: '../build/gaia2.pc'

**Comment by echo66** [comment]
I forgot to answer this, Dmitry. The problem seems to be with the option --with-stlfacade. Any idea why? Without that, it compiles just fine.

**Comment by dbogdanov** [comment]
I don't think it is related; ```with-stlfacade``` builds some more cpp files, but this would not affect the problem with missing ```gaia2.pc```

**Comment by doronbehar** [comment]
@dbogdanov I'm encountering the same error in a sandboxed build environment (meaning I shouldn't _need_ to run `./waf clean` before the build because it's a clean environment to begin with). Disabling the `--with-stlfacade` flag fixes this.
