### ISSUE TITLE
Error when training model

### ISSUE THREAD

**Issue by alastair** [MTG/gaia#48]
```
2016-07-28 10:22:27,631 - INFO - Processing job cba7d880-04ca-4e02-8517-deb5619f3b0f...
INFO     ClassificationTaskManager  |  Merging original base dataset...
2016-07-28 10:22:27,710 - INFO - Merging original base dataset...
Harmonizing chunks so that they all have the same layout & history...
Traceback (most recent call last):
  File "evaluate.py", line 181, in <module>
    main()
  File "evaluate.py", line 35, in main
    evaluate_dataset(pending_job)
  File "evaluate.py", line 69, in evaluate_dataset
    filelist_file=filelist_path,
  File "/home/acousticbrainz/acousticbrainz-server/dataset_eval/../dataset_eval/gaia_wrapper.py", line 47, in train_model
    run_tests(project_file)
  File "/home/acousticbrainz/ve/local/lib/python2.7/site-packages/gaia2/scripts/classification/run_tests.py", line 55, in runTests
    test.run()
  File "/home/acousticbrainz/ve/local/lib/python2.7/site-packages/gaia2/classification/classificationtaskmanager.py", line 177, in run
    self.mergeDataSet()
  File "/home/acousticbrainz/ve/local/lib/python2.7/site-packages/gaia2/classification/classificationtaskmanager.py", line 170, in mergeDataSet
    mergeAll(self.conf['filelist'], self.conf['datasetFilename'], 5000, transfoFile = None)
  File "/home/acousticbrainz/ve/local/lib/python2.7/site-packages/gaia2/fusion.py", line 160, in mergeAll
    vldescs, nandescs, rdescs = harmonizeChunks(partfiles)
  File "/home/acousticbrainz/ve/local/lib/python2.7/site-packages/gaia2/fusion.py", line 86, in harmonizeChunks
    ds.load(partfiles[0])
IndexError: list index out of range
```

**Comment by djb2017** [comment]
![image](https://cloud.githubusercontent.com/assets/20794222/18193707/b4cf7f54-7112-11e6-9126-31026909979d.png)
