### ISSUE TITLE
train_model yaml scaner error 

### ISSUE THREAD

**Issue by pabx06** [MTG/gaia#67]
hello.
i am using  latest instable master version of gaia & essentia 
i tuned `/usr/local/lib/python2.7/dist-packages/gaia2/scripts/classification/classification_project_template.yaml`

then
`user@localhost $python /usr/local/lib/python2.7/dist-packages/gaia2/scripts/classification/train_model.py  groundtruth_example.yaml filelist_example.yaml genret genre_t resmod 2>output`

i end up with :
**resmod.results.html** empty file.
many **genre_t/datasets/*.db**
many **genre_t/results/*.{result,param}**

LAST console outputs:

INFO     ClassificationTask  |  Running evaluation 0 for: /home/user/dataset/genres/genre_t/results/genre_tzanetakis1845179432983635467 with classifier svm and dataset basic
INFO     ClassificationTask  |      PID: 20215, parameters: {"kernel": "poly", "C": -5, "preprocessing": "basic", "type": "C-SVC", "classifier": "svm", "gamma": 1}
INFO     ClassificationTask  |  Running evaluation 0 for: /home/user/dataset/genres/genre_t/results/genre_tzanetakis1845177432955635541 with classifier svm and dataset basic
INFO     ClassificationTask  |      PID: 20216, parameters: {"kernel": "poly", "C": -5, "preprocessing": "basic", "type": "C-SVC", "classifier": "svm", "gamma": 3}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gaia2/scripts/classification/train_model.py", line 92, in <module>
    trainModel(groundtruth_file, filelist_file, project_file, project_dir, results_model_file)
  File "/usr/local/lib/python2.7/dist-packages/gaia2/scripts/classification/train_model.py", line 68, in trainModel
    select_best_model.selectBestModel(project_file, results_model_file)
  File "/usr/local/lib/python2.7/dist-packages/gaia2/scripts/classification/select_best_model.py", line 31, in selectBestModel
    project = yaml.load(open(project_file, 'r'))
  File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/lib/python2.7/dist-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 110, in compose_sequence_node
    while not self.check_event(SequenceEndEvent):
  File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 486, in parse_flow_sequence_entry
    if self.check_token(KeyToken):
  File "/usr/lib/python2.7/dist-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/lib/python2.7/dist-packages/yaml/scanner.py", line 257, in fetch_more_tokens
    % ch.encode('utf-8'), self.get_mark())
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "genret", line 40, column 1
![image](https://user-images.githubusercontent.com/4013370/32320438-1404d5f0-bfbe-11e7-8e19-96bbb9866bac.png)

**Comment by pabx06** [comment]
a bit confused. any idea where are the svm models... and where could i look to fix it
